# Default values for kube-deploy
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  targetPort: 80
  # metricsPort: 8080  # Optional metrics port
  # sessionAffinity: None  # Optional session affinity

# Gateway/HTTPRoute configuration (optional)
gateway:
  enabled: false
  annotations: {}
  parentRefs: []
    # - name: traefik-gateway
    #   namespace: traefik
    #   sectionName: websecure
  hostnames: []
    # - "example.com"
  rules: []
    # - matches:
    #     - path:
    #         type: PathPrefix
    #         value: /

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

volumes: []
volumeMounts: []

# ConfigMap configuration (optional)
configMap:
  enabled: false
  data: {}
    # Example:
    # ASPNETCORE_ENVIRONMENT: "Production"
    # DATABASE_HOST: "postgres.default.svc.cluster.local"
    # RABBITMQ_HOST: "rabbitmq.default.svc.cluster.local"

# Additional environment variables (optional)
env: []
  # Example:
  # - name: MY_ENV_VAR
  #   value: "my-value"
  # - name: SECRET_VALUE
  #   valueFrom:
  #     secretKeyRef:
  #       name: my-secret
  #       key: password

nodeSelector: {}

tolerations: []

affinity: {}

# Monitoring Configuration (optional)
monitoring:
  enabled: false
  serviceMonitor:
    enabled: false
    interval: 30s
    scrapeTimeout: 10s
    path: /metrics
    labels: {}
      # release: kps

# mTLS Configuration (optional)
mtls:
  enabled: false
  containerPort: 8443
  servicePort: 443

  ca:
    commonName: "Root CA"
    issuerName: selfsigned-issuer
    issuerKind: ClusterIssuer
    duration: 87600h  # 10 years
    renewBefore: 8760h  # 1 year

  server:
    commonName: "server"
    dnsNames: []
      # - service.namespace.svc.cluster.local
    ipAddresses: []
    duration: 2160h  # 90 days
    renewBefore: 720h  # 30 days

  client:
    commonName: "client"
    duration: 2160h  # 90 days
    renewBefore: 720h  # 30 days

# Health Check Configuration (optional)
healthCheck:
  liveness:
    enabled: false
    path: /health/live
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

  readiness:
    enabled: false
    path: /health/ready
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 5
    failureThreshold: 3