{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "kube-deploy.fullname" . }}
  labels:
    {{- include "kube-deploy.labels" . | nindent 4 }}
  {{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.gateway.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.gateway.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
  {{- range .Values.gateway.rules }}
  - matches:
    {{- range .matches }}
    - path:
        type: {{ .path.type }}
        value: {{ .path.value }}
    {{- end }}
    backendRefs:
    - name: {{ include "kube-deploy.fullname" $ }}
      port: {{ $.Values.service.port }}
  {{- end }}
{{- end }}