name: Release Helm Chart

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Package Helm Chart
        run: |
          helm package .

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Update Helm Repository
        run: |
          # Create gh-pages directory if it doesn't exist
          mkdir -p gh-pages

          # Copy the packaged chart to gh-pages
          cp *.tgz gh-pages/ 2>/dev/null || true

          # Update the index
          helm repo index gh-pages --url https://vitorafgomes.github.io/kube-deploy

          # Configure git
          cd gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Add and commit
          git add .
          git commit -m "Update Helm chart repository" || exit 0
          git push origin gh-pages

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'gh-pages'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4